### ISSUE TITLE
Not working on magento 2.4.6

### ISSUE THREAD

**Issue by AxxaGroup** [cap340/M2DeletedProductImage#17]
```
There is an error in /home/axxagrou/public_html/vendor/symfony/console/Command/Command.php at line: 301
Return value of "Cap\CleanMedia\Console\Command\CleanMedia\Interceptor::execute()" must be of the type int, "null" returned.#0 /home/axxagrou/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Symfony\Component\Console\Command\Command->run()
#1 /home/axxagrou/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Cap\CleanMedia\Console\Command\CleanMedia\Interceptor->___callParent()
#2 /home/axxagrou/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Cap\CleanMedia\Console\Command\CleanMedia\Interceptor->Magento\Framework\Interception\{closure}()
#3 /home/axxagrou/public_html/generated/code/Cap/CleanMedia/Console/Command/CleanMedia/Interceptor.php(23): Cap\CleanMedia\Console\Command\CleanMedia\Interceptor->___callPlugins()
#4 /home/axxagrou/public_html/vendor/symfony/console/Application.php(1040): Cap\CleanMedia\Console\Command\CleanMedia\Interceptor->run()
#5 /home/axxagrou/public_html/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#6 /home/axxagrou/public_html/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun()
#7 /home/axxagrou/public_html/vendor/symfony/console/Application.php(171): Magento\Framework\Console\Cli->doRun()
#8 /home/axxagrou/public_html/bin/magento(23): Symfony\Component\Console\Application->run()
#9 {main}
```

I believe it deletes the files but doesn't seem to be able to delete from the database now.

I know this hasn't been updated for 5 years but just in case anyone is still on it.

Thanks!

**Comment by gerben86** [comment]
Same issue overhere.
@AxxaGroup : did you find a solution for it?

**Comment by gerben86** [comment]
Solved by adding return 0; at the end of the execute() function in Console/Command/CleanMedia.php
